Update sharedmemtest-c++.yml

diff --git a/.github/workflows/sharedmemtest-c++.yml b/.github/workflows/sharedmemtest-c++.yml
--- a/.github/workflows/sharedmemtest-c++.yml
+++ b/.github/workflows/sharedmemtest-c++.yml
@@ -1,9 +1,11 @@
 name: shared-mem-test-c++
 
+env:
+  usingSharedMem: ''
 on:
   push:
     branches:
-      - 'main'
+      - 'sharedmem'
 
 jobs:
 
@@ -29,4 +31,9 @@ jobs:
        -
         name: Build and run
         run: |
-          cd clients/c++ && ./build.sh && ./http-client model:4242
+          cd clients/c++ && ./build.sh && checkShMem=$(./http-client model:4242 | grep -o "not accessible"); echo "CheckShMem=$checkShMem" >> $GITHUB_ENV
+       -
+        name: Check if Shared Memory is used
+        if: $CheckShMem == "not accessible"
+        run: |
+            echo "Shared Memory not available, failed"; exit 1
