Try with additional shm flag

diff --git a/.github/workflows/sharedmemtest-c++.yml b/.github/workflows/sharedmemtest-c++.yml
--- a/.github/workflows/sharedmemtest-c++.yml
+++ b/.github/workflows/sharedmemtest-c++.yml
@@ -19,7 +19,7 @@ jobs:
         image: linusseelinger/model-exahype-tsunami
         ports:
         - 4242:4242
-        options: --ipc=host
+        options: --ipc=host --shm-size=1gb
 
     steps:
        -
@@ -32,5 +32,9 @@ jobs:
        -
         name: Build and run
         run: |
-          cd clients/c++ && ./build.sh && ./http-client model:4242
-
+          cd clients/c++ && ./build.sh && checkShMem=$(./http-client model:4242 | grep -o "not accessible"); echo "CheckShMem=$checkShMem" >> $GITHUB_ENV
+       -
+        name: Check if Shared Memory is used
+        if: env.CheckShMem == 'not accessible'
+        run: |
+            echo "Shared Memory not available, failed"; exit 1
diff --git a/.github/workflows/sharedmemtest-python.yml b/.github/workflows/sharedmemtest-python.yml
--- a/.github/workflows/sharedmemtest-python.yml
+++ b/.github/workflows/sharedmemtest-python.yml
@@ -17,7 +17,7 @@ jobs:
         image: linusseelinger/model-exahype-tsunami:latest
         ports:
         - 4242:4242
-        options: --ipc=host
+        options: --ipc=host --shm-size=1gb
 
     steps:
        -
@@ -32,4 +32,9 @@ jobs:
         run: |
           python3 -m venv venv
           . venv/bin/activate && pip3 install umbridge
-          cd clients/python && python3 -u umbridge-client.py http://model:4242
+          cd clients/python && checkShMem=$(python3 umbridge-client.py http://model:4242 | grep -o "not accessible"); echo "CheckShMem=$checkShMem" >> $GITHUB_ENV
+       - 
+        name: Check if Shared Memory is used
+        if: env.CheckShMem == 'not accessible'
+        run: |
+            echo "Shared Memory not available, failed"; exit 1
